version: 2

jobs:
  plan-apply:
    working_directory: /tmp/terraform
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply:
          context: AWS
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          context: AWS
          requires:
            - hold-apply
